/usr/bin/uuidgen: /apps/spack/gilbreth/apps/anaconda/2020.11-py38-gcc-4.8.5-djkvkvk/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
/home/vciroski/.local/lib/python3.8/site-packages/pydot.py:17: UserWarning: `pydot` could not import `dot_parser`, so `pydot` will be unable to parse DOT files. The error was:  No module named 'pyparsing'
  warnings.warn(
There was a problem when trying to write in your cache folder (/depot/euge/etc/models). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
Traceback (most recent call last):
  File "langchain_hard.py", line 365, in <module>
    image_to_text_tool = ImageToTextTool()
  File "langchain_hard.py", line 34, in __init__
    pipe = pipeline(
  File "/home/vciroski/.conda/envs/cent7/2020.11-py38/elab_2/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 747, in pipeline
    resolved_config_file = cached_file(
  File "/home/vciroski/.conda/envs/cent7/2020.11-py38/elab_2/lib/python3.8/site-packages/transformers/utils/hub.py", line 430, in cached_file
    resolved_file = hf_hub_download(
  File "/home/vciroski/.conda/envs/cent7/2020.11-py38/elab_2/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/vciroski/.conda/envs/cent7/2020.11-py38/elab_2/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/home/vciroski/.conda/envs/cent7/2020.11-py38/elab_2/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/depot/euge/etc/models/models--facebook--nougat-base'
srun: error: gilbreth-k027: task 0: Exited with exit code 1
